version: '3.8'

services:
  spinner:
    image: repo.alexmaisa.my.id/alexmaisa/spinner:latest
    container_name: spinner-app
    ports:
      - "8080:8080"
    volumes:
      - spinner-data:/app/data
    env_file:
      - .env
    restart: always

volumes:
  spinner-data:
